######################################################################
# Automatically generated by qmake (2.01a) Fri Feb 8 21:49:52 2008
######################################################################

TEMPLATE = app
TARGET = be-client
DEPENDPATH += .
INCLUDEPATH += .
QT += network

# Input
HEADERS += view.h
SOURCES += main.cpp view.cpp
