CC = g++
CXXFLAGS = -O3  -pg -fprofile-arcs -ftest-coverage
LDFLAGS = -pg -fprofile-arcs -ftest-coverage

default: clean test-eric
clean:
	-rm -f test-eric *.o
test-eric: test-eric.o
test-eric.o:  test-eric.cpp erisick.cpp Timer.hpp
