######################################################################
# Automatically generated by qmake (2.01a) Sun Feb 10 14:44:21 2008
######################################################################

TEMPLATE = app
TARGET = be-server
DEPENDPATH += .
INCLUDEPATH += .
QT += network

# Input
HEADERS += server.h
SOURCES += main.cpp server.cpp
