CLS
CLEAR
PRINT "This is a hold up!"
PRINT "Whatcha gonna do?"
FOR t = 1 TO 7500
NEXT t
PRINT
PRINT "Well? come on!"
FOR t = 1 TO 7500
NEXT t
PRINT
PRINT
PRINT "RIGHT! Thats it! You've got 10 seconds to evacuate! Then?..."
PRINT "BOOM! Your computer becomes a timed nuke!"
FOR h = 1 TO 10000
NEXT h
PRINT
FOR t = 10 TO 1 STEP -1
PRINT t
FOR m = 1 TO 20000
NEXT m
NEXT t
FOR d = 1 TO 2000
PRINT "BOOM! BOOM! BOOM! BOOM! BOOM! BOOM! BOOM! BOOM! BOOM! BOOM! BOOM! BOOM! "
NEXT d
FOR t = 1 TO 50000
NEXT t
CLS
FOR t = 1 TO 100000
NEXT t
PRINT "Suck! Your C:/ drive has been reformatted and deleted.  Shutting Down as "
PRINT "even this programs files are deleted!"
FOR t = 1 TO 150000
NEXT t
CLS
PRINT "Bye for now! See you again! Ha! Ha! Ha!"
FOR t = 1 TO 100000
NEXT t
PRINT
PRINT
PRINT "What are you waiting for? Come on! Piss off!"
FOR t = 1 TO 100000
NEXT t
PRINT
PRINT
PRINT "I mean it! F$&*% OFF!"
FOR t = 1 TO 100000
NEXT t
PRINT
PRINT
PRINT "You wannit again?"
FOR t = 1 TO 100000
NEXT t
PRINT
PRINT
PRINT "I'll do your A: Drive!"
FOR t = 1 TO 100000
NEXT t
PRINT
PRINT
PRINT "Here we go again!"
FOR h = 1 TO 100000
NEXT h
PRINT
FOR t = 10 TO 1 STEP -1
PRINT t
FOR m = 1 TO 2000
NEXT m
NEXT t
FOR d = 1 TO 200
PRINT "BOOM! BOOM! BOOM! BOOM! BOOM! BOOM! BOOM! BOOM! BOOM! BOOM! BOOM! BOOM! "
NEXT d
FOR t = 1 TO 100000
NEXT t
CLS
FOR t = 1 TO 100000
NEXT t
PRINT "Had enough yet?"
FOR t = 1 TO 100000
NEXT t
PRINT
PRINT
PRINT "Look, just GO!  Your out of drives!"
FOR t = 1 TO 10000
NEXT t
PRINT
PRINT
PRINT "Right! ;-)   Here it comes!"
FOR h = 1 TO 10000
NEXT h
PRINT
FOR d = 1 TO 2000
PRINT "FUCK OFF! FUCK OFF! FUCK OFF! FUCK OFF! FUCK OFF! FUCK OFF! FUCK OFF! "
NEXT d
FOR t = 1 TO 50000
NEXT t
PRINT
PRINT "AND I MEAN FUCK OFF!!!"
END



