######################################################################
# Automatically generated by qmake (2.01a) Sun Feb 10 13:22:00 2008
######################################################################

TEMPLATE = app
TARGET =
DEPENDPATH += .
INCLUDEPATH += . ../tibia

# Input
SOURCES += main.cpp
